version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:03"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
    groups:
      flake-inputs:
        patterns:
          - "*"
