version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "57 20 * * *"
      timezone: "Asia/Shanghai"
    groups:
      flake-inputs:
        patterns:
          - "*"
