name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - ci-test
  workflow_dispatch:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: NixOS/nix-installer-action@446de1db899ec21d0e00635be184b72c6c4ff9a7
        with:
          extra-conf: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix flake check
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: NixOS/nix-installer-action@446de1db899ec21d0e00635be184b72c6c4ff9a7
        with:
          extra-conf: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix run .#checkLinks -- .
